### ISSUE TITLE
inject hangs when used with Fastify async handler fulfilling undefined

### ISSUE THREAD

**Issue by simoneb** [fastify/light-my-request#217] opened 2022-08-21 19:03 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x but happening in previous versions as well

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

This is an issue related to how this library behaves when used with Fastify. Fastify supports async route handlers and it supports those handlers fulfilling the returned promise with undefined (e.g. not returning anything from the handler).

Example:

```js
fastify.get('/', async () => {
  // implicitly returns a promise fulfilled with undefined
})
```

When `.inject` is used on such routes, it never returns/resolves, and the reason is that Fastify has a special handling for these cases, which is captured ]here](https://github.com/fastify/fastify/blob/d3c3ad78060dd356ef174a45c9585fb36643db7e/lib/wrapThenable.js#L20-L21).

You can see that it handles the behavior of these route handlers so that either they do not resolve undefined, OR the other condition, which requires that:

```js
reply.sent === false && reply.raw.headersSent === false && reply.request.raw.aborted === false
```

The first 2 conditions are satisfied by this library, whereas the third isn't. The fix is fairly straightforward and it's to add that `aborted = false` property to the Request object exposed by this library. Nonetheless before doing this fix I thought it would make sense to discuss whether this change should be done here as it's so specific to how Fastify uses this library.

### Steps to Reproduce

See https://github.com/fastify/fastify/issues/4207

**Comment by Uzlopak** [comment] 2022-08-21 19:55
Shouldnt be the solution to set aborted to false?

**Comment by simoneb** [comment] 2022-08-21 21:13
> Shouldnt be the solution to set aborted to false?

That was a typo I corrected but that's not the point. What I was trying to convey is if such a fastify-specific fix should be done here

**Comment by Uzlopak** [comment] 2022-08-21 21:30
It is just for clarity. 

The issue is more reply.request.raw is afaik nodejs http request object. So it is https://nodejs.org/api/http.html#requestaborted So we should actually also set the destroyed attribute to false. 

And yes I think setting aborted and destroyed should be done in this package.

**Comment by mcollina** [comment] 2022-08-22 08:28
This should be fixed here, and it's not fastify specific.

**Closed** 2022-08-22 08:54 UTC
